dataset_reader:
  type: goodnews_flattened
  tokenizer:
    type: word
    word_splitter: just_spaces
  token_indexers:
    roberta:
      type: roberta
      model_name: roberta-base
      namespace: bpe
      padding_on_right: true
      padding_value: 1
      max_len: 512
  image_dir: data/goodnews/images_processed
  eval_limit: 5120
  lazy: true
train_data_path: train
validation_data_path: val
test_data_path: test
vocabulary:
  type: roberta
  directory_path: ./expt/vocabulary
model:
  type: baseline
  use_context: true
  pool_type: none
  evaluate_mode: false
  topk: 1
  vocab_size: 50265
  hidden_size: 1024
  attention_dim: 1024
  namespace: bpe
  index: roberta
  padding_value: 1
  initializer:
    - - ^(attention|article_attention|init|f).*weight
      - type: xavier_uniform
    - - ^(attention|article_attention|init|f).*bias
      - type: zero
    - - ^rnn_cell.*weight
      - type: xavier_uniform
    - - ^rnn_cell.*bias
      - type: zero
iterator:
  type: bucket
  sorting_keys:
    - - context
      - num_tokens
    - - caption
      - num_tokens
  batch_size: 16
  max_instances_in_memory: 2048
  biggest_batch_first: false
  instances_per_epoch: 65536
  maximum_samples_per_batch: ["num_tokens", 4096]
validation_iterator:
  type: bucket
  sorting_keys:
    - - context
      - num_tokens
    - - caption
      - num_tokens
  batch_size: 16
  max_instances_in_memory: 2048
  maximum_samples_per_batch: ["num_tokens", 4096]
  biggest_batch_first: false
trainer:
  type: callback_apex
  apex_opt_level: O2 # keep softmax computation at full precision
  keep_batchnorm_fp32: None
  optimizer:
    type: bert_adam
    lr: 0.0005
    warmup: 0.05
    t_total: 680000 # Takees 1h 20m to go through 6800 batches per epoch
    schedule: warmup_linear
    b1: 0.9
    b2: 0.98
    e: 0.000001
    weight_decay: 0.00001 # Worse choices: 0.01, 0.001, 0.000001
    max_grad_norm: 0.1 # Worse choices: 1.0
    parameter_groups:
      - - - ^attention
        - {}
      - - - ^init
        - {}
      - - - ^f
        - {}
      - - - ^rnn_cell
        - {}
  no_grad:
    - ^resnet
    - ^roberta
  num_epochs: 100
  shuffle: true
  cuda_device: 0
  callbacks:
    - type: checkpoint
    - type: track_metrics
      patience: 10
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 512
      should_log_parameter_statistics: false
      log_batch_size_period: 1024
