dataset_reader:
  type: nytimes
  tokenizer:
    type: word
    word_splitter: just_spaces
  token_indexers:
    roberta:
      type: roberta
      model_name: roberta-base
      namespace: bpe
      padding_on_right: true
      padding_value: 1
  image_dir: data/nytimes/images
  lazy: true
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: roberta
  directory_path: ./expt/vocabulary
model:
  type: baseline
  use_context: true
  topk: 1
  vocab_size: 50265
  hidden_size: 1024
  attention_dim: 1024
  namespace: bpe
  index: roberta
  padding_value: 1
  initializer:
    - - ^(attention|article_attention|init|f).*weight
      - type: xavier_uniform
    - - ^(attention|article_attention|init|f).*bias
      - type: zero
    - - ^rnn_cell.*weight
      - type: xavier_uniform
    - - ^rnn_cell.*bias
      - type: zero
iterator:
  type: bucket
  sorting_keys:
    - - caption
      - num_tokens
  batch_size: 2
  max_instances_in_memory: 2048
  biggest_batch_first: false
  instances_per_epoch: 4000
validation_iterator:
  type: bucket
  sorting_keys:
    - - caption
      - num_tokens
  batch_size: 4
  max_instances_in_memory: 2048
  biggest_batch_first: false
  instances_per_epoch: 1000
trainer:
  type: callback_apex
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adam_w
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 0.000001
    weight_decay: 0.00001
    correct_bias: true
    parameter_groups:
      - - - ^attention
        - {}
      - - - ^init
        - {}
      - - - ^f
        - {}
      - - - ^rnn_cell
        - {}
  no_grad:
    - ^resnet
    - ^roberta
  num_epochs: 20
  shuffle: true
  cuda_device: 0
  callbacks:
    - type: checkpoint
    - type: track_metrics
      patience: 500
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 500
      should_log_parameter_statistics: false
      log_batch_size_period: 5000
    - type: update_learning_rate
      learning_rate_scheduler:
        type: slanted_triangular
        num_epochs: 40
        num_steps_per_epoch: 2000
        cut_frac: 0.1
        ratio: 32
        gradual_unfreezing: false
        discriminative_fine_tuning: false
        decay_factor: 0.38
